/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tec;

public class App {
	public static void main(String[] args) {
		String nombre = "Axel";
		System.out.println("Hola "+ nombre);
	}
}
